# render.yaml
# ────────────────────────────────────────────────
# Barangay Health Center Monitoring & Scheduling System
# Laravel + PostgreSQL + Gmail SMTP (Docker-based)
# ────────────────────────────────────────────────

services:
  - type: web
    name: bhcmss
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false  # Safer for production: manual deploys
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://bhcmss.onrender.com

      # Database connection - Production Postgres via Supabase
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_DATABASE
        sync: false  # Set in dashboard: your Supabase database name
      - key: DB_HOST
        sync: false  # Set in dashboard: your-project.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_USERNAME
        sync: false  # Set in dashboard: from Supabase connection info
      - key: DB_PASSWORD
        sync: false  # Set in dashboard: from Supabase connection info

      # Cache and session settings for production
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"

      # ------------------------------------------------------------------
      # Example: switch to external Postgres (recommended for production)
      # ------------------------------------------------------------------
      # To use an external Postgres (Supabase/Neon/ElephantSQL), set DB_CONNECTION
      # to `pgsql` and set DB_HOST/DB_PORT/DB_DATABASE/DB_USERNAME/DB_PASSWORD in
      # the Render dashboard (or include them here with secure values). Example:
      #
      # - key: DB_CONNECTION
      #   value: pgsql
      # - key: DB_HOST
      #   value: your-db-host.supabase.co
      # - key: DB_PORT
      #   value: 5432
      # - key: DB_DATABASE
      #   value: your_database_name
      # - key: DB_USERNAME
      #   value: your_db_user
      # - key: DB_PASSWORD
      #   value: your_db_password
      #
      # See DEPLOY.md for step-by-step instructions to create a free Supabase or
      # Neon database and wire it into Render.

      # Gmail SMTP for reminders
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false   # Set in Render dashboard
      - key: MAIL_PASSWORD
        sync: false   # Set in Render dashboard (App Password)
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: no-reply@bhcmss.com
      - key: MAIL_FROM_NAME
        value: BHCMSS Notifications

## Note: Managed database removed from `render.yaml` when using SQLite for free plan.
## If you later want to use Render-managed Postgres, add the `databases:` section back
## and set DB_CONNECTION=pgsql in the envVars. SQLite is recommended for quick demos on
## free plans but not for production use.
