# render.yaml
# ────────────────────────────────────────────────
# Barangay Health Center Monitoring and Scheduling System
# Laravel + PostgreSQL + Gmail SMTP + Free-tier Render deployment
# ────────────────────────────────────────────────

services:
  - type: web
    name: bhcmss
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://bhcmss.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bhcmss-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bhcmss-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bhcmss-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bhcmss-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bhcmss-db
          property: password
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false   # Add manually in Render dashboard
      - key: MAIL_PASSWORD
        sync: false   # Add manually in Render dashboard (App Password)
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: no-reply@bhcmss.onrender.com
      - key: MAIL_FROM_NAME
        value: BHCMSS Notifications

databases:
  - name: bhcmss-db
    plan: free
    databaseName: bhcmss
    user: bhcmss_user
