# render.yaml
# ────────────────────────────────────────────────
# Barangay Health Center Monitoring & Scheduling System
# Laravel + PostgreSQL + Gmail SMTP (Docker-based)
# ────────────────────────────────────────────────

services:
  - type: web
    name: bhcmss
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://bhcmss.onrender.com

      # Database connection
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bhcmss-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bhcmss-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bhcmss-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bhcmss-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bhcmss-db
          property: password

      # Gmail SMTP for reminders
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false   # Set in Render dashboard
      - key: MAIL_PASSWORD
        sync: false   # Set in Render dashboard (App Password)
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: no-reply@bhcmss.com
      - key: MAIL_FROM_NAME
        value: BHCMSS Notifications

databases:
  - name: bhcmss-db
    plan: free
    databaseName: bhcmss
    user: bhcmss_user
