<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Appointments Report - {{ ucfirst($reportType) }} - {{ $month }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
            flex-wrap: wrap;
        }
        .stat-box {
            background: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
            min-width: 120px;
            margin: 5px;
        }
        .stat-box h3 {
            margin: 0;
            font-size: 18px;
            color: #2c5aa0;
        }
        .stat-box p {
            margin: 5px 0 0 0;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Doctor Appointments Report</h1>
        <p><strong>Report Type:</strong> {{ ucfirst($reportType) }}</p>
        <p><strong>Period:</strong> {{ \Carbon\Carbon::createFromFormat('Y-m', $month)->format('F Y') }}</p>
        <p><strong>Generated on:</strong> {{ now()->format('M d, Y H:i') }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <h3>{{ $stats['total_records'] }}</h3>
            <p>Total Appointments</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['completed'] }}</h3>
            <p>Completed</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['upcoming'] }}</h3>
            <p>Upcoming</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['cancelled'] }}</h3>
            <p>Cancelled</p>
        </div>
    </div>

    <h2>Appointments Summary</h2>
    <table>
        <thead>
            <tr>
                <th>Patient Name</th>
                <th>Appointment Date</th>
                <th>Status</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
                <tr>
                    <td>{{ $record->patient->full_name ?? 'N/A' }}</td>
                    <td>{{ $record->appointment_date ? $record->appointment_date->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ ucfirst($record->status) }}</td>
                    <td>{{ Str::limit($record->notes ?? '', 50) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center;">No appointments found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by the BHCMS system.</p>
        <button class="no-print" onclick="window.print()" style="margin-top: 20px; padding: 10px 20px; background: #2c5aa0; color: white; border: none; border-radius: 5px; cursor: pointer;">Print Report</button>
    </div>
</body>
</html>
